### SBM Database Fild For Underwritten Life & Disability

### Where :

- ULD -> Underwriter Life Disability

- LIFE_DI -> Life Disability Insurance

- ULD_SUBGROUPS → subgroup information

- ULD_BILLING_ENROLL → billing/enrollment data

- ULD_CONTACTS → contact details

- ULD_SOLD_RATES → sold/premium rate information

## Table Codes : Suffix Description
----------------------------------------------------
|  Suffix  | Description                           |
|----------|---------------------------------------|
|BL        | Basic Life                            |
|SL        | Supplemental Life                     |
|DL        | Dependent Life                        |
|SDL       | Supplemental Dependent Life           |
|SDLS      | Supplemental Dependent Life Spouse    |
|SDLC      | Supplemental Dependent Life Child     |
|BADD      | Basic AD&D                            |
|SADD      | Supplemental AD&D                     |
|DADD      | Dependent AD&D                        |
|SDADD     | Supplemental Dependent AD&D           |
|STD       | Short Term Disability                 |
|STDBU     | STD Buy-Up                            |
|LTD       | Long Term Disability                  |
|LTDBU     | LTD Buy-Up                            |
|GI        | General Information / Guaranteed Issue|

In [123]:
# Import Load the pakages
import os
import numpy as np
import pandas as pd
from sqlalchemy import create_engine
from dotenv import load_dotenv
import pyodbc

from dotenv import load_dotenv
import os
import pyodbc
from sqlalchemy import create_engine

In [124]:
print(pyodbc.drivers())

['SQL Server', 'ODBC Driver 18 for SQL Server']

## DataBase Connection Details

In [125]:
load_dotenv()
server = os.getenv("DB_SERVER")
database = os.getenv("DB_DATABASE")
user = os.getenv("DB_USER")
password = os.getenv("DB_PASSWORD")
print("ServerName:",server)
print("DatabaseName :",database)
print("User :", user)

ServerName: WP000163446CLS
DatabaseName : Teamtrack_AE
User : eoi_process_pr

## Connect Database

In [126]:
server = os.getenv("DB_SERVER")
database = os.getenv("DB_DATABASE")
user = os.getenv("DB_USER")
password = os.getenv("DB_PASSWORD")
conn_str = (
    f"mssql+pyodbc://{user}:{password}@{server}/{database}"
    "?driver=ODBC+Driver+18+for+SQL+Server"
    "&TrustServerCertificate=yes"
)
engine = create_engine(conn_str)

## Extract Under Writer Disability Life insurance  Table ULD_LIFE_DI

In [127]:
import pandas as pd
data_df = pd.read_sql(
    "select * from ULD_LIFE_DI",
    engine)
data_df.shape

(85891, 969)

In [128]:
data_df.head()

,TS_ID,TS_UUID,TS_ISSUEID,TS_UNDERWRITER,TS_CASE_SETUP,TS_SUBMITTER,TS_BILLING,TS_COMMISSIONS,TS_CONTRACTS,TS_WELCOME_LETTER,...,TS_NUMBER_OF_CERTIFICATES_CR,TS_NUMBER_OF_CERTIFICATES_PA,TS_ONBASE_UPDATED_PA,TS_IF_YES_PORTABILITY_SERVICE,TS_HIST_TAKE_LEAVE_RECVDATE,TS_HISTORICAL_TAKEOVER_LEAVE_,TS_MANUAL_DEMOGRAPHIC_FILE_ST,TS_MANUAL_DEMOGRAPHIC_FILE_RE,TS_EOI_CONFIRMATION_E_MAIL_ST,TS_CONVERSION_COVERAGE_APPLIE
0,0,none,NaN,0,0,0,0,0,0,0,...,NaN,NaN,0.0,",",NaT,0,0,NaT,0,","
1,25,55679df7-2c29-48d5-b202-9bbf0e31315f,000006,2427,2573,1563,4693,2747,0,0,...,NaN,NaN,0.0,",",NaT,0,0,NaT,0,","
2,26,29453141-6936-4bcd-b20b-9886402ee43b,000001,1929,843,1487,1795,1743,0,0,...,NaN,NaN,0.0,",",NaT,0,0,NaT,0,","
3,27,b1d6a1a7-3ee4-48a7-b680-67ee5ec81cce,000003,2427,843,1489,1592,1743,0,0,...,NaN,NaN,0.0,",",NaT,0,0,NaT,0,","
4,28,4378eb75-1ca4-41b7-b858-3ef8516e2c75,000002,1553,843,1487,1548,1743,0,0,...,NaN,NaN,0.0,",",NaT,0,0,NaT,0,","

## Selected Fild and Map to ULD_LIFE_DI Table

In [129]:
select_map_uld_life_di_query="""
SELECT
    TS_IS_SUPP_CHILD_DL_AMT_LIM,
    TS_IS_SUPP_SPOUSE_DL_AMT_LIM,
    TS_PART_REQ_MET_SDL,
    TS_NA_TAKEOVER_FOR_EE_SDLS,
    TS_EOI_REQ_NEWLY_ELIG_EE_SDLS,
    TS_EOI_NEW_HIRE_OVER_GI_SDLS,
    TS_EOI_COV_31_DAYS_SDLS,
    TS_EOI_FOR_INCR_COV_SDLS,
    TS_EOI_FOR_1_BENE_LVL_SDLS,
    TS_1_BENE_LEVEL_EQUALS_SDLS,
    TS_OTHER_EOI_SDLS,
    TS_EOI_REQ_IF_ELECT_COV_OESDL,
    TS_CURRENT_EE_NO_BL_SDL,
    TS_CURRENT_EE_INCREASE_AMT_SD,
    TS_COMMENTS_BADD,
    TS_COMMENTS_BL,
    TS_COMMENTS_BUSTD,
    TS_COMMENTS_DADD,
    TS_COMMENTS_DL,
    TS_COMMENTS_GI,
    TS_COMMENTS_LTD,
    TS_COMMENTS_LTDBU,
    TS_COMMENTS_SADD,
    TS_COMMENTS_SDADD,
    TS_COMMENTS_SDL,
    TS_COMMENTS_SL,
    TS_COMMENTS_STD,
    TS_BEN_PERCENT_BU_STD,
    TS_GUAR_ISS_ONETIME_OE_LTDBU,
    TS_GUAR_ISSUE_ANNUAL_OE_LTDBU,
    TS_EXP_GUAR_ISSUE_AMT_BULTD,
    TS_LTD_BUYUP_OPTION,
    TS_MAX_MONTH_BU_OPTION_LTD,
    TS_OE_OFFER_LTDBU,
    TS_OE_TERM_DATE_LTDBU,
    TS_GROUP_POLICY_NUMBER,
    TS_GROUP_NAME,
    TS_SITUS_STATE,
    TS_PLAN_ANNIV_DATE,
    TS_DEFINE_EARNINGS_SL,
    TS_EFFECTIVE_DATE_SDL,
    TS_EFFECTIVE_DATE_SL,
    TS_GUAR_ISSUE_AMT_BL,
    TS_GUAR_ISSUE_AMT_SL,
    TS_REDUCE_SCH_SL,
    TS_ROUNDING_SL,
    TS_TERMINATION_DATE_SDL,
    TS_TERMINATION_DATE_SL,
    TS_VIRGIN_LINE_COVERAGE_SL,
    TS_BENEFIT_PERCENTAGE_STD,
    TS_MAX_WEEK_BENE_STD,
    TS_ELIM_PERIOD_SICK_STD,
    TS_ELIM_PERIOD_INJ_STD,
    TS_STD_MIN_PARTICIPATE_STD,
    TS_STD_GUARANTEE_STD,
    TS_TERMINATION_DATE_STD,
    TS_EFFECTIVE_DATE_STD
FROM ULD_LIFE_DI"""

uld_life_di_data = pd.read_sql(
   select_map_uld_life_di_query,
    engine
)
uld_life_di_data.shape

(85891, 57)

In [169]:
uld_life_di_data.head(10)

,TS_IS_SUPP_CHILD_DL_AMT_LIM,TS_IS_SUPP_SPOUSE_DL_AMT_LIM,TS_PART_REQ_MET_SDL,TS_NA_TAKEOVER_FOR_EE_SDLS,TS_EOI_REQ_NEWLY_ELIG_EE_SDLS,TS_EOI_NEW_HIRE_OVER_GI_SDLS,TS_EOI_COV_31_DAYS_SDLS,TS_EOI_FOR_INCR_COV_SDLS,TS_EOI_FOR_1_BENE_LVL_SDLS,TS_1_BENE_LEVEL_EQUALS_SDLS,...,TS_TERMINATION_DATE_SL,TS_VIRGIN_LINE_COVERAGE_SL,TS_BENEFIT_PERCENTAGE_STD,TS_MAX_WEEK_BENE_STD,TS_ELIM_PERIOD_SICK_STD,TS_ELIM_PERIOD_INJ_STD,TS_STD_MIN_PARTICIPATE_STD,TS_STD_GUARANTEE_STD,TS_TERMINATION_DATE_STD,TS_EFFECTIVE_DATE_STD
0,0,0,0,0,0,0,0,0,0,NaN,...,NaT,0,0,0,0,0,0,0,NaT,NaT
1,0,0,0,0,0,0,0,0,0,NaN,...,NaT,0,0,0,0,0,0,0,NaT,NaT
2,0,0,0,0,0,0,0,0,0,NaN,...,NaT,0,0,0,0,0,0,0,NaT,NaT
3,0,0,0,0,0,0,0,0,0,NaN,...,NaT,0,0,0,0,0,0,0,NaT,NaT
4,0,0,0,0,0,0,0,0,0,NaN,...,NaT,0,0,0,0,0,0,0,NaT,NaT
5,0,0,0,0,0,0,0,0,0,NaN,...,NaT,0,0,0,0,0,0,0,NaT,NaT
6,0,0,0,0,0,0,0,0,0,NaN,...,NaT,0,0,0,0,0,0,0,NaT,NaT
7,0,0,0,0,0,0,0,0,0,NaN,...,NaT,0,0,0,0,0,0,0,NaT,NaT
8,0,0,0,0,0,0,0,0,0,NaN,...,NaT,0,0,0,0,0,0,0,NaT,NaT
9,0,0,0,0,0,0,0,0,0,NaN,...,NaT,0,0,0,0,0,0,0,NaT,NaT

In [131]:
#General Infomation
general_case_info_query="""SELECT 
    TS_GROUP_NAME , 
    TS_GROUP_POLICY_NUMBER,
    TS_GROUP_EFFECTIVE_DATE,
    TS_PLAN_ANNIV_DATE,
    TS_SITUS_STATE,
    TS_NUM_OF_EE,
    TS_TYPE_OF_BUSINESS,
    TS_SIC_CODE,
    TS_UNDERWRITER,
    TS_ACCOUNT_MANAGER
FROM ULD_LIFE_DI"""

general_info_df = pd.read_sql(
    general_case_info_query,
    engine
)
print(general_info_df.shape)

(85891, 10)

In [156]:
general_info_df.head(10)

,TS_GROUP_NAME,TS_GROUP_POLICY_NUMBER,TS_GROUP_EFFECTIVE_DATE,TS_PLAN_ANNIV_DATE,TS_SITUS_STATE,TS_NUM_OF_EE,TS_TYPE_OF_BUSINESS,TS_SIC_CODE,TS_UNDERWRITER,TS_ACCOUNT_MANAGER
0,NaN,NaN,NaT,NaN,0,NaN,0,NaN,0,0
1,The Decorating Business LTD,310488,2006-09-01,09/01,10278,2,10036,7389,2427,1795
2,"Protocol Link, Inc",311150,2008-06-01,06/01,10258,15,10036,8742,1929,999
3,Red Brown Kle Inc,310678,2007-05-01,05/01,10292,4,10036,8742,2427,999
4,CONGRESSIONAL MANAGEMENT FOUNDATION,311159,2008-06-01,06/01,10251,NaN,10036,8742,1553,999
5,Eastern Industrial Maintenance,311162,2008-06-01,6/1,10289,16,10040,1796,1553,999
6,Community Printing Inc,310690,2007-05-01,05/01,10292,9,10036,2752,2427,999
7,Schutt Industries of Clintonville WI Inc,311163,2008-06-01,6/1,10292,62,10036,3715,1929,999
8,Astro Tool & Die Corporation,310693,2007-05-01,05/01,10292,48,10036,3544,1553,1752
9,Gateway Holdings LLC,311051,2008-03-01,03/01,10268,10,10036,7338,1553,1752

In [168]:
#check the policy number Null value
general_info_df.loc[general_info_df["TS_GROUP_POLICY_NUMBER"].isna(),["TS_GROUP_NAME", "TS_GROUP_POLICY_NUMBER"]].head(10)

  TS_GROUP_NAME TS_GROUP_POLICY_NUMBER
0           NaN                    NaN

In [165]:
#Removing the Null Values of policy Number 
result_df = general_info_df.loc[
general_info_df["TS_GROUP_POLICY_NUMBER"].notna(),
["TS_GROUP_POLICY_NUMBER", "TS_GROUP_NAME"]]
result_df.head(15)

   TS_GROUP_POLICY_NUMBER                             TS_GROUP_NAME
1                  310488               The Decorating Business LTD
2                  311150                        Protocol Link, Inc
3                  310678                         Red Brown Kle Inc
4                  311159       CONGRESSIONAL MANAGEMENT FOUNDATION
5                  311162            Eastern Industrial Maintenance
6                  310690                    Community Printing Inc
7                  311163  Schutt Industries of Clintonville WI Inc
8                  310693              Astro Tool & Die Corporation
9                  311051                      Gateway Holdings LLC
10                 311164                      Kaeden Services, Inc
11                 310709      Huth - Ben Pearson International LLC
12                 310710             Interstate Tool & Engineering
13                 310741                       SH Enterprises Inc.
14                 310677             J.Z. RUSSELL INDUSTRIES, INC.
15                 310588               Orange County Healthy Start

In [133]:
data_df_contact = pd.read_sql(
    "select * from ULD_CONTACTS",
    engine
)
data_df_contact.shape

(39415, 100)

In [134]:
data_df_contact.head()

,TS_ID,TS_UUID,TS_TITLE,TS_CONTACT_TYPE,TS_ASSOCIATED_CONTACTS,TS_LINK_TO_SOLD_CASE,TS_NAME_DTD,TS_NAME_AFF_AGENCY,TS_ADDRESS_AFF_AGENT,TS_ADDRESS,...,TS_GENERAL_AGENT_PRODUCER_ID,TS_ACCIDENT_PROTECTION_REPORT,TS_HOSPITAL_INDEMNITY,TS_EXPL_HOSP_INDEMNITY_COMM,TS_EXPLAIN_SUPP_HEALTH_COMBO_,TS_LIST_STATES_WITH_STATE_PAI,TS_EXPLAIN_STATE_PAID_LEAVE_C,TS_STATE_PAID_LEAVE,TS_SUPP_HEALTH_COMBO,TS_OHID
0,115,38fbdc3a-f92a-40e9-99c8-a5dd9dee8290,None,10528,0,1251,NaN,NaN,NaN,NaN,...,NaN,0,0,NaN,NaN,NaN,NaN,0,0,NaN
1,116,546fd8f3-8c82-4317-af43-3ae272abbb6f,None,10526,0,1251,Martin Kooper,Gallagher Benefit Services,770 Lexington Avenue,"1075 Park Avenue, #6D",...,NaN,0,0,NaN,NaN,NaN,NaN,0,0,NaN
2,117,a013e252-d43c-46ed-b10b-efe40536b5a8,None,10528,0,1097,NaN,NaN,NaN,NaN,...,NaN,0,0,NaN,NaN,NaN,NaN,0,0,NaN
3,119,682e93f7-56df-46a0-ac30-086f51d96176,None,10528,0,1271,NaN,NaN,NaN,NaN,...,NaN,0,0,NaN,NaN,NaN,NaN,0,0,NaN
4,121,ec3e4464-a962-431d-b36e-9a34a6123a47,None,10526,0,1251,Martin Kooper,Gallagher Benefit Services,"1075 Park Avenue, #6D",770 Lexington Avenue,...,NaN,0,0,NaN,NaN,NaN,NaN,0,0,NaN

## Selected Fields of Contact Table

In [135]:
data_df_subgroup = pd.read_sql(
    "select * from ULD_SUBGROUPS",
    engine
)
data_df_subgroup.shape

(28089, 85)

In [136]:
data_df_subgroup.head()

,TS_ID,TS_UUID,TS_ISSUEID,TS_ASSOCIATED_SUBGROUPS,TS_SUBGROUP_NAME,TS_SUBGROUP_NUMBER,TS_SUBGROUP_PURPOSE,TS_ADDRESS_CON1,TS_ADDRESS_CON2,TS_CSZ_CON1,...,TS_ACCIDENT_COMMISSIONS_UMB,TS_EXPLAIN_ACCIDENT_COMM_UMB,TS_AGENCY_ADDRESS_SAA_UMB,TS_AGENCY_NAME_UMB,TS_AGENCY_ADDRESS_UMB,TS_AGENCY_CITY_STATE_ZIP_UMB,TS_AGENCY_PHONE_UMB,TS_AGENCY_FAX_UMB,TS_AGENCY_PRODUCER_ID_UMB,TS_AGENCY_TAX_ID_NO_UMB
0,97,171a57e3-076e-4852-9941-0421d7140eb3,08304,0,NaN,1000,",",: 5201 S Whitnall Ave,NaN,"Cudahy, WI 53110",...,0,None,",",None,None,None,None,None,None,None
1,98,859057f3-c6c1-48a7-860c-17eb45ab775d,08305,0,NaN,1000,",",185 Industrial Ave,NaN,Clintonville WI 54929,...,0,None,",",None,None,None,None,None,None,None
2,99,4616c5b5-644d-49c1-866e-5c3d5c532bc9,08307,0,NaN,1000,",",23 Wakefield Ave.,NaN,"Coram, NY 11727",...,0,None,",",None,None,None,None,None,None,None
3,100,01fc55b0-a5da-45d9-b558-6aeef0bd31fc,08306,0,NaN,1000,",",175 E Hawthorn Parkwaysuite 210,NaN,Vernon Hills\tIL 60061,...,0,None,",",None,None,None,None,None,None,None
4,101,4f05189b-0588-45a6-8193-83826d344c14,08310,0,NaN,1000,",",4455 Telegraph Road Ste 160,NaN,"St. Louis, MO 63129",...,0,None,",",None,None,None,None,None,None,None

In [137]:
data_df_billing_enroll = pd.read_sql(
    "select * from ULD_BILLING_ENROLL",
    engine
);
data_df_subgroup.shape

(28089, 85)

In [138]:
data_df_billing_enroll.head()

,TS_ID,TS_UUID,TS_TITLE,TS_AGE_BAND_RATE_EFFECT,TS_COMMENTS,TS_ASO_CLAIM_DEP_AMT,TS_ASO_CLAIM_CHECK_BILL,TS_ASO_DEPOSIT_TYPE,TS_BILL_ADJUST_PERIOD,TS_COMM_RETAIN_PAYEE,...,TS_EMPLOYEE_PAID_STATE_PAID_L,TS_SHC_ER_PAID_TAX_METHOD,TS_SHC_EE_PAID_TAX_METHOD,TS_SPL_ER_PAID_TAX_METHOD,TS_SPL_EE_PAID_TAX_METHOD,TS_SUPP_HEALTH_COMBO_BILLING_,TS_EMPLOYER_PAID_SPL_MEDICAL,TS_EMPLOYER_PAID_SPL_FAMILY,TS_EMPLOYEE_PAID_SPL_MEDICAL,TS_EMPLOYEE_PAID_SPL_FAMILY
0,73,fa11a9c1-6d96-400c-86e1-be3801aec8f5,None,0,NaN,0.0,0,0,0,0,...,NaN,0,0,0,0,0,NaN,NaN,NaN,NaN
1,74,aa3a6fc5-f3ae-42dc-b7a1-4b7bbb71b000,None,0,NaN,0.0,0,0,0,0,...,NaN,0,0,0,0,0,NaN,NaN,NaN,NaN
2,75,d62d83e8-4076-43f4-9724-37a09435c7b2,None,0,NaN,0.0,0,0,0,0,...,NaN,0,0,0,0,0,NaN,NaN,NaN,NaN
3,76,441181c0-16bd-480b-b79f-c967fc506d4a,None,0,NaN,0.0,0,0,0,0,...,NaN,0,0,0,0,0,NaN,NaN,NaN,NaN
4,78,7d5c5c44-64b2-4d9d-bd05-1525195620f7,None,0,NaN,0.0,0,0,0,0,...,NaN,0,0,0,0,0,NaN,NaN,NaN,NaN

In [139]:
data_df_solid_rate= pd.read_sql(
    "select * from ULD_SOLD_RATES",
    engine
)
data_df_solid_rate.shape

(76622, 327)

In [140]:
data_df_solid_rate.head()

,TS_ID,TS_UUID,TS_TITLE,TS_LINK_TO_SOLD_CASE,TS_ASSOCIATED_SOLD_RATES_,TS_PRODUCT,TS_AMOUNT_AND_MAX_BENEFIT,TS_CLASS_CODE,TS_INSURANCE_CLASS_OF_EE,TS_NUMBER_OF_EMPLOYEES,...,TS_FMLA_COMMENTS,TS_FMLA_PRODUCT_REINSTA,TS_FMLA_PRODUCT_REINSTATEMENT,TS_COMPANY_SPECIFIC_LEAVES_MA,TS_TOTAL_FMLA_MONTHLY_FEE,TS_FMLA_INFORMATION_METHOD,TS_CORE_PREMIUMS,TS_BUY_UP_PREMIUMS,TS_CORE_TAXABILITY,TS_BUY_UP_TAXABILITY
0,126,df570c46-8c16-4ca3-a410-f337d4074e1d,None,1251,0,10387,"1 x Salary to $175,000 max",1,Management,10.0,...,NaN,NaT,None,NaN,NaN,0,NaN,NaN,0,0
1,129,455d5efd-9e30-4224-ade3-b098a2e763da,None,1251,0,10386,"1 x Salary to $175,000 max",1,Management,10.0,...,NaN,NaT,None,NaN,NaN,0,NaN,NaN,0,0
2,130,387b6300-31aa-464e-881f-7238d4bb111e,None,1251,0,10387,"$70,000",2,All Other Acive Full-Time Employees,24.0,...,NaN,NaT,None,NaN,NaN,0,NaN,NaN,0,0
3,131,031e5f7f-d6a7-48f8-a19d-c6b673fe9fd0,None,1251,0,10386,"$70,000",2,All Other Active Full-Time Employees,24.0,...,NaN,NaT,None,NaN,NaN,0,NaN,NaN,0,0
4,132,cbc3a36b-9020-4de8-be55-4d2e39572d01,None,1251,0,10391,NaN,1 & 2,All Active Full-Time Employees,0.0,...,NaN,NaT,None,NaN,NaN,0,NaN,NaN,0,0

In [141]:
import pandas as pd
df = pd.read_sql(
    "select TS_ID,TS_UUID, TS_GROUP_NAME,TS_GROUP_POLICY_NUMBER,TS_STATE, TS_PLAN_ANNIV_DATE from ULD_LIFE_DI;",
    engine
)

In [142]:
df.shape

(85891, 6)

In [143]:
df.head(10)

,TS_ID,TS_UUID,TS_GROUP_NAME,TS_GROUP_POLICY_NUMBER,TS_STATE,TS_PLAN_ANNIV_DATE
0,0,none,NaN,NaN,0,NaN
1,25,55679df7-2c29-48d5-b202-9bbf0e31315f,The Decorating Business LTD,310488,392,09/01
2,26,29453141-6936-4bcd-b20b-9886402ee43b,"Protocol Link, Inc",311150,392,06/01
3,27,b1d6a1a7-3ee4-48a7-b680-67ee5ec81cce,Red Brown Kle Inc,310678,392,05/01
4,28,4378eb75-1ca4-41b7-b858-3ef8516e2c75,CONGRESSIONAL MANAGEMENT FOUNDATION,311159,392,06/01
5,29,b964ff6e-873d-42d6-ac09-54314e4cbc77,Eastern Industrial Maintenance,311162,392,6/1
6,30,9723a615-1ca4-4310-9494-fca998e9000f,Community Printing Inc,310690,392,05/01
7,31,4d162105-e1c2-4f8a-a16d-6d08307aa71b,Schutt Industries of Clintonville WI Inc,311163,392,6/1
8,32,30c1131b-6f76-4a7e-a3a2-3dac55e05b07,Astro Tool & Die Corporation,310693,392,05/01
9,33,f307d42c-7498-4ce3-96a1-5b33307a9981,Gateway Holdings LLC,311051,392,03/01

In [144]:
import orjson
# DataFrame -> list of dicts -> JSON bytes
json_data = orjson.dumps(df.to_dict(orient="records"))
# If string needed
json_str = json_data.decode("utf-8")

In [145]:
# table 
df2 = pd.read_sql(
    "select * from USR_VISION_MEDICAID_ELIG;",
    engine
)

In [146]:
df2.columns

Index(['TS_ID', 'TS_UUID', 'TS_ISSUETYPE', 'TS_ISSUEID', 'TS_TITLE',
       'TS_REQUEST_TYPE', 'TS_ACTION_REQUESTED', 'TS_UPDATE_TYPE',
       'TS_MEMBER_IDS', 'TS_MEMBER_NAMES', 'TS_MEMBER_DOB', 'TS_CLAIM_NUMBER',
       'TS_HEALTH_PLAN_INFORMATION', 'TS_ADDRESS', 'TS_ELIG_COORDINATOR',
       'TS_SUBMITTER_LITE', 'TS_COB_OUTCOME', 'TS_ELIG_VERIFICATION_OUTCOME',
       'TS_MERGE_UNMERGE_OUTCOME', 'TS_DOS', 'TS_DUE_DATE', 'TS_GENDER',
       'TS_PHONE_NUMBER', 'TS_EFFECTIVE_DATE', 'TS_RESOLUTION',
       'TS_COB_INFORMATION', 'TS_MEMBER_NAME_2', 'TS_MEMBER_NAME_3',
       'TS_MEMBER_NAME_4', 'TS_MEMBER_ID_2', 'TS_MEMBER_ID_3',
       'TS_MEMBER_ID_4', 'TS_MEMBER_DOB_2', 'TS_MEMBER_DOB_3',
       'TS_MEMBER_DOB_4', 'TS_MEMBER_ADDRESS_2', 'TS_MEMBER_ADDRESS_3',
       'TS_MEMBER_ADDRESS_4', 'TS_DATE', 'TS_TIME_SPENT_HR',
       'TS_TIME_SPENT_MIN', 'TS_NAME_USER_ID', 'TS_RESOLUTIONSUMMARY',
       'TS_SUBMITTER', 'TS_SUBMITDATE', 'TS_CLOSEDATE',
       'TS_LASTSTATECHANGEDATE', 'TS_ACTIVEINACTIVE', 'TS_PROJECTID',
       'TS_STATE', 'TS_OWNER', 'TS_LASTMODIFIEDDATE', 'TS_LASTMODIFIER',
       'TS_LASTSTATECHANGER'],
      dtype='str')

## To View the Table USR_VISION_MEDICAID_ELIG  few table

In [147]:
df2[['TS_ID', 'TS_UUID', 'TS_MEMBER_IDS','TS_MEMBER_NAMES','TS_CLAIM_NUMBER']]

,TS_ID,TS_UUID,TS_MEMBER_IDS,TS_MEMBER_NAMES,TS_CLAIM_NUMBER
0,0,none,NaN,NaN,NaN
1,18,723f2ef0-3d65-495d-89f5-51ee43a2d50d,114025946/114025948,Alayna/laura Fleming,NaN
2,19,56a15017-7fed-438f-893f-35ff160e947a,114025946. 2nd member ID# 114025948,Alayna Fleming & Laura Fleming,n/a
3,20,aeda8464-86f0-44b5-af43-82ce03a649a7,000250582,"NAPENAS, NINA",29698089
4,21,0b6c7123-188f-4b91-8cf3-4ca53e66761d,116592033,"CARLTON, SAMANTHA",29747792
...,...,...,...,...,...
14240,15436,b6f02761-d360-46c8-85c7-1c91933de47b,655000494604,Casey Mercer,29577779
14241,15437,1904ef3c-df57-4ebc-beb5-6c792fdfd31e,00110224108,"WILSON, LEEANN",34440491
14242,15438,71260dcb-c2ef-49d2-b210-d489e44591c9,112693991,"MOOTS, LUCAS",34178114
14243,15439,619d6801-d860-45ad-b597-4f4a7ded3532,3580710I,"FEDDERSEN, EASTYN",34466273
14244,15440,d97ed866-028a-41a7-a426-8ea82004228a,383641780,"NEWELL, JANIQUA",34468314

## Mapping Fild of the TBM Table ULD_LIFE_DI

In [148]:
sql_query= """SELECT TS_ID,TS_GROUP_POLICY_NUMBER AS GROUP_NUMBER, TS_GROUP_NAME AS EMPLOYER_NAME,
TS_SITUS_STATE AS SITUS_STATE,
TS_PLAN_ANNIV_DATE AS PLAN_ANNIVERSARY_DATE,
TS_GUAR_ISSUE_AMT_BL AS BASIC_LIFE_GI_AMOUNT,
TS_GUAR_ISSUE_AMT_SL AS SUPP_LIFE_GI_AMOUNT,
TS_BEN_PERCENT_LTD AS LTD_BENEFIT_PERCENTAGE,
TS_BENEFIT_PERCENTAGE_STD AS STD_BENEFIT_PERCENTAGE,
TS_MAX_MONTH_BEN_LTD AS MAXIMUM_MONTHLY_BENEFIT,
TS_MAX_WEEK_BENE_STD AS MAXIMUM_WEEKLY_BENEFIT,
TS_OTHER_SP_SL AS SPOUSE_ELIGIBILITY_COMMENT,
TS_EXP_LIMIT_SDL_SPOUSE AS SPOUSE_COVERAGE_LIMIT_COMMENT,
TS_COMMENTS_BL AS BASIC_LIFE_COMMENTS,
TS_COMMENTS_SL AS SUPP_LIFE_COMMENTS,
TS_COMMENTS_LTD AS LTD_COMMENTS,
TS_COMMENTS_STD AS STD_COMMENTS
FROM ULD_LIFE_DI"""

map_df = pd.read_sql(sql_query,engine)

In [149]:
map_df

,TS_ID,GROUP_NUMBER,EMPLOYER_NAME,SITUS_STATE,PLAN_ANNIVERSARY_DATE,BASIC_LIFE_GI_AMOUNT,SUPP_LIFE_GI_AMOUNT,LTD_BENEFIT_PERCENTAGE,STD_BENEFIT_PERCENTAGE,MAXIMUM_MONTHLY_BENEFIT,MAXIMUM_WEEKLY_BENEFIT,SPOUSE_ELIGIBILITY_COMMENT,SPOUSE_COVERAGE_LIMIT_COMMENT,BASIC_LIFE_COMMENTS,SUPP_LIFE_COMMENTS,LTD_COMMENTS,STD_COMMENTS
0,0,NaN,NaN,0,NaN,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1,25,310488,The Decorating Business LTD,10278,09/01,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
2,26,311150,"Protocol Link, Inc",10258,06/01,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
3,27,310678,Red Brown Kle Inc,10292,05/01,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,28,311159,CONGRESSIONAL MANAGEMENT FOUNDATION,10251,06/01,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85886,110044,307986,"Harbor Retirement Associates, LLC",10253,09/01,"Class 1 & Class 2 - $50,000\r\nClass 3 - $150,000","$200,000",9424,9434,9789,9791,NaN,NaN,Definition of Earnings: Class 1&2- The Annual ...,9/1/2025A one-time exception for a Limited Ope...,"Evidence of Insurability NA, No new entrants a...",1x OE is allowed
85887,110045,305304,"Lone Star Milk Transport, Inc.",10287,01/01,"$50,000","$75,000",9424,9434,9788,9792,NaN,NaN,marked Yes for NAAW ees on App; no list of NAA...,Explain Portability Benefits (Sup Life): The ...,Maximum Benefit Period (LTD): Class 2: Reducin...,NaN
85888,110046,307986,"Harbor Retirement Associates, LLC",10253,09/01,"Class 1 & Class 2 - $50,000\r\nClass 3 - $150,000","$200,000",9424,9434,9789,9791,NaN,NaN,Definition of Earnings: Class 1&2- The Annual ...,9/1/2025A one-time exception for a Limited Ope...,"Evidence of Insurability NA, No new entrants a...",1x OE is allowed
85889,110047,373689,Aligned Dental Payroll Services Corporation,10253,01/01,"$25,000","$100,000",9424,9434,9785,9792,NaN,100%,NaN,NaN,1x OE at time of sale,1X OE at time of sale
85890,110048,372094,Sonova U.S. Corporate Services LLC,10258,01/01,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

### Product specific view

### Supplemental Life (SL), which is where GI and spouse limits are most common

In [150]:
sql_query2= """SELECT
    TS_GROUP_POLICY_NUMBER AS GROUP_NUMBER,
    TS_GROUP_NAME          AS EMPLOYER_NAME,
    TS_SITUS_STATE         AS SITUS_STATE,
    TS_PLAN_ANNIV_DATE     AS PLAN_ANNIVERSARY_DATE,
    TS_GUAR_ISSUE_AMT_SL   AS GI_AMOUNT,
    TS_OTHER_SP_SL         AS SPOUSE_ELIGIBILITY_COMMENT,
    TS_EXP_LIMIT_SDL_SPOUSE AS SPOUSE_COVERAGE_LIMIT_COMMENT,
    TS_COMMENTS_SL         AS PRODUCT_COMMENTS,
    TS_RENEWAL_NOTICE_DAYS_SL AS RENEWAL_DATE
FROM ULD_LIFE_DI"""
sl_map_df = pd.read_sql(sql_query2,engine)

In [151]:
sl_map_df.head()

,GROUP_NUMBER,EMPLOYER_NAME,SITUS_STATE,PLAN_ANNIVERSARY_DATE,GI_AMOUNT,SPOUSE_ELIGIBILITY_COMMENT,SPOUSE_COVERAGE_LIMIT_COMMENT,PRODUCT_COMMENTS,RENEWAL_DATE
0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,0
1,310488,The Decorating Business LTD,10278,09/01,NaN,NaN,NaN,NaN,0
2,311150,"Protocol Link, Inc",10258,06/01,NaN,NaN,NaN,NaN,0
3,310678,Red Brown Kle Inc,10292,05/01,NaN,NaN,NaN,NaN,0
4,311159,CONGRESSIONAL MANAGEMENT FOUNDATION,10251,06/01,NaN,NaN,NaN,NaN,0

In [152]:
sql_query3="""SELECT
    TS_GROUP_POLICY_NUMBER,
    TS_GROUP_NAME,
    TS_SUPP_LIFE AS PRODUCT,
    TS_EFFECTIVE_DATE_SL AS EFFECTIVE_DATE,
    TS_TERMINATION_DATE_SL AS TERMINATION_DATE,
    TS_SL_PLAN_DESIGN AS INSURANCE_CLASS,
    TS_GUAR_ISSUE_AMT_SL,
    TS_COVERAGE_TERMS_SL,
    TS_COMMENTS_SL
FROM ULD_LIFE_DI"""
Supplemental_Life= pd.read_sql(sql_query3,engine)

In [153]:
Supplemental_Life

,TS_GROUP_POLICY_NUMBER,TS_GROUP_NAME,PRODUCT,EFFECTIVE_DATE,TERMINATION_DATE,INSURANCE_CLASS,TS_GUAR_ISSUE_AMT_SL,TS_COVERAGE_TERMS_SL,TS_COMMENTS_SL
0,NaN,NaN,0,NaT,NaT,0,NaN,0,NaN
1,310488,The Decorating Business LTD,10000,NaT,NaT,0,NaN,0,NaN
2,311150,"Protocol Link, Inc",10000,NaT,NaT,0,NaN,0,NaN
3,310678,Red Brown Kle Inc,10000,NaT,NaT,0,NaN,0,NaN
4,311159,CONGRESSIONAL MANAGEMENT FOUNDATION,10000,NaT,NaT,0,NaN,0,NaN
...,...,...,...,...,...,...,...,...,...
85886,307986,"Harbor Retirement Associates, LLC",9999,2020-09-01,NaT,15484,"$200,000",9508,9/1/2025A one-time exception for a Limited Ope...
85887,305304,"Lone Star Milk Transport, Inc.",9999,2018-01-01,NaT,0,"$75,000",9508,Explain Portability Benefits (Sup Life): The ...
85888,307986,"Harbor Retirement Associates, LLC",9999,2020-09-01,NaT,15484,"$200,000",9508,9/1/2025A one-time exception for a Limited Ope...
85889,373689,Aligned Dental Payroll Services Corporation,9999,2026-01-01,NaT,15485,"$100,000",9508,NaN
85890,372094,Sonova U.S. Corporate Services LLC,10000,NaT,NaT,0,NaN,0,NaN